version: "3"

tasks:
  switch:
    cmds:
      - NIXPKGS_ALLOW_UNFREE=1 home-manager switch --impure --flake .

  rebuild:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update:
    cmds:
      - nix flake update

  fmt:
    cmds:
      - nixfmt ./

  dev:
    cmds:
      - nix develop

  news:
    cmds:
      - home-manager news --flake .

  daily:
    cmds:
      - task: update
      - task: fmt
      - git add flake.lock
      - 'git commit -m "build: update lock file"'
      - git push
      - task: switch
      - task: clean

  clean:
    cmds:
      - home-manager expire-generations "-14 days"
      - nix store gc -v --log-format bar-with-logs