version: "3"

tasks:
  switch:
    cmds:
      - home-manager switch --flake .

  rebuild:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update:
    cmds:
      - nix flake update

  fmt:
    cmds:
      - nixfmt ./

  dev:
    cmds:
      - nix develop
