version: "3"

tasks:
  switch:
    cmds:
      - NIXPKGS_ALLOW_UNFREE=1 home-manager switch --impure --flake .

  rebuild:
    cmds:
      - sudo nixos-rebuild switch --flake .

  update:
    cmds:
      - nix flake update

  fmt:
    cmds:
      - nixfmt ./

  dev:
    cmds:
      - nix develop

  news:
    cmds:
      - home-manager news --flake .