function source {
  ensure_zcompiled $1
  builtin source $1
}

function ensure_zcompiled {
  local compiled="$1.zwc"
  if [[ ! -r "$compiled" || "$1" -nt "$compiled" ]]; then
    echo "\033[1;36mCompiling\033[m $1"
    zcompile $1
  fi
}

ensure_zcompiled "${HOME}/.config/zsh/.zshrc"

autoload -U promptinit; promptinit

# sheldon cache technique
sheldon_path="${HOME}/.config/sheldon"
sheldon_cache="${sheldon_path}/sheldon.zsh"
sheldon_toml="${sheldon_path}/plugins.toml"
if [[ ! -r "$sheldon_cache" || "$sheldon_toml" -nt "$sheldon_cache" ]]; then
  sheldon source > $sheldon_cache
fi
source "$sheldon_cache"
unset sheldon_path sheldon_cache sheldon_toml

zsh-defer zstyle :prompt:pure:git:stash show yes
zsh-defer zstyle ':completion:*' menu select