" basic setting
set number
set notitle
set ruler
set noswapfile
" set ambiwidth=double
set cursorline
set tabstop=2
set expandtab
set shiftwidth=2
set smartindent
set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
set nrformats-=octal
set hidden
set history=100
set virtualedit=block
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start
set wildmenu
syntax on
set hlsearch
set ignorecase
set incsearch
set smartcase
set laststatus=2
set autoindent
